Created unit tests for `QueryTemplateModel`
hypertool/hypertool pull request #79
Opened 2022-01-28 18:58 UTC by pranjal5399

2022-01-29 04:54 UTC, itssamuelrowe requested changes

2022-01-29 04:54 UTC, itssamuelrowe commented on packages/api/test/helper/constants.ts
> +        name: "abc",
Use values that are more realistic. For example, the name could be "getUsers".

2022-01-29 04:54 UTC, itssamuelrowe commented on packages/api/test/helper/constants.ts
> +        description: "lorem ipsum dolor amet",
And the description could be "Gets the list of users who have placed an order."

2022-01-29 04:54 UTC, itssamuelrowe commented on packages/api/test/helper/constants.ts
> +        content: "abcd",
And the content could be `SELECT * FROM users as u LEFT JOIN orders as o ON u.id=o.userId`

2022-01-29 04:54 UTC, itssamuelrowe commented on packages/api/test/models/queryTemplate.test.ts
> +describe("QueryTemplate Model", function () {
`QueryTemplate model`

The message that you specify to `describe` and the message that you specify to `it` are combined to form a sentence in the output. Keep that in mind.

2022-01-29 04:54 UTC, itssamuelrowe commented on packages/api/test/models/queryTemplate.test.ts
> +            name: new Array(129 + 1).join("a"),
Good!

2022-01-29 04:54 UTC, itssamuelrowe commented on packages/api/test/models/queryTemplate.test.ts
> +            "The status attribute is not from defined origins.",
"origins"?

2022-01-30 10:32 UTC, itssamuelrowe requested changes

2022-01-30 10:32 UTC, itssamuelrowe commented on packages/api/test/helper/constants.ts
> +            "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBIVFBgVEhIYGBgYGBgYGBIaGBIYGhocGBoZGRkaGBkcIS4lHB4rHxgYJjgmKy8xNTU1GiQ7QDszPy40NTEBDAwMEA8QHhISHDQhISE0NDQ0NDQ0NDQ0NDQ0NDE0NDE
What is this? You can use a smaller link like: https://i.picsum.photos/id/496/400/400.jpg?hmac=8or0mw_rugRSBRDFhLAj770EHslVmfHZEu0a_NKkxoY

2022-01-30 10:32 UTC, itssamuelrowe commented on packages/api/test/models/queryTemplate.test.ts
> +    it("should not be created when status is undefined", async () => {
`QueryTemplate` can be created without `status`. You can remove this test case.

2022-01-30 10:32 UTC, itssamuelrowe commented on packages/common/test/models/resource.test.ts
> +    it("should not be created when name is undefined", async () => {
Update `ResourceModel` to add `required: true` to `name` attribute.

```
        name: {
            type: String,
            minlength: 0,
            maxlength: 256,
            trim: true,
            required: true
        },     
```

2022-01-30 10:32 UTC, itssamuelrowe commented on packages/common/test/models/resource.test.ts
> +    it("should not be created when name is null", async () => {
If you add required to `name` attribute, this test case will also pass.

2022-01-30 10:32 UTC, itssamuelrowe commented on packages/api/test/models/user.test.ts
> +    it("should not be created when gender is undefined", async () => {
It seems like you haven't deleted the files from the API package. :/

2022-01-31 07:34 UTC, joelerego approved these changes

2022-01-31 07:51 UTC, itssamuelrowe approved these changes

2022-01-31 07:52 UTC, merged